/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerHome;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import model.Aluno;
import java.sql.Connection;
import javax.swing.JButton;
import view.PlaylistFrame;
import view.CurtidasFrame;
import view.HistoricoFrame;
import controller.ControllerPlaylist;
import javax.swing.JOptionPane;

/**
 *
 * @author RJUTWE
 */
    public class EditPlaylistFrame extends javax.swing.JFrame {
        private ControllerPlaylist controllerPlaylist;
        private Connection conn;
        private Aluno aluno;
        private PlaylistFrame playlistFrame;

    public EditPlaylistFrame(Connection conn, Aluno aluno, PlaylistFrame playlistFrame) {
        this.conn = conn;
        this.aluno = aluno;
        this.playlistFrame = playlistFrame;
        initComponents();

        controllerPlaylist = new ControllerPlaylist(conn, playlistFrame, aluno); 
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_id_playlist = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_musica_id = new javax.swing.JTextField();
        btn_apagar_musica = new javax.swing.JButton();
        btn_apagar_playlist = new javax.swing.JButton();
        btn_adicionar_musica = new javax.swing.JButton();
        btn_fechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        lbl_id_playlist.setBackground(new java.awt.Color(51, 51, 51));
        lbl_id_playlist.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID Playlist");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Musicas (id)");

        lbl_musica_id.setBackground(new java.awt.Color(51, 51, 51));
        lbl_musica_id.setForeground(new java.awt.Color(255, 255, 255));

        btn_apagar_musica.setBackground(new java.awt.Color(102, 102, 102));
        btn_apagar_musica.setForeground(new java.awt.Color(255, 255, 255));
        btn_apagar_musica.setText("Apagar Musica");
        btn_apagar_musica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_apagar_musicaMouseClicked(evt);
            }
        });

        btn_apagar_playlist.setBackground(new java.awt.Color(102, 102, 102));
        btn_apagar_playlist.setForeground(new java.awt.Color(255, 255, 255));
        btn_apagar_playlist.setText("Apagar Playlist");
        btn_apagar_playlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_apagar_playlistMouseClicked(evt);
            }
        });

        btn_adicionar_musica.setBackground(new java.awt.Color(102, 102, 102));
        btn_adicionar_musica.setForeground(new java.awt.Color(255, 255, 255));
        btn_adicionar_musica.setText("Adicionar Musica");
        btn_adicionar_musica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_adicionar_musicaMouseClicked(evt);
            }
        });

        btn_fechar.setBackground(new java.awt.Color(102, 102, 102));
        btn_fechar.setForeground(new java.awt.Color(255, 255, 255));
        btn_fechar.setText("Fechar");
        btn_fechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_fecharMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_apagar_musica, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_apagar_playlist, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_adicionar_musica, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_fechar, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lbl_id_playlist, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_musica_id, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_id_playlist, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_musica_id, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_apagar_musica, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_apagar_playlist, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_adicionar_musica, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_fechar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_fecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_fecharMouseClicked
       this.dispose();
    }//GEN-LAST:event_btn_fecharMouseClicked

    private void btn_adicionar_musicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_adicionar_musicaMouseClicked
         String idStr = lbl_id_playlist.getText().trim();
         String musicasStr = lbl_musica_id.getText().trim();

    if (idStr.isEmpty() || musicasStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Informe o ID da playlist e as músicas.");
        return;
    }

    try {
        int idPlaylist = Integer.parseInt(idStr);
        String[] musicas = musicasStr.split(",");
        controllerPlaylist.adicionarMusicasNaPlaylist(idPlaylist, musicas);
        controllerPlaylist.carregarPlaylists();
        this.setVisible(false);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "ID inválido.");
    }
    }//GEN-LAST:event_btn_adicionar_musicaMouseClicked

    private void btn_apagar_musicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_apagar_musicaMouseClicked
    String idStr = lbl_id_playlist.getText().trim();
    String musicasStr = lbl_musica_id.getText().trim();

    if (idStr.isEmpty() || musicasStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Informe o ID da playlist e as músicas a remover.");
        return;
    }

    try {
        int idPlaylist = Integer.parseInt(idStr);
        String[] musicas = musicasStr.split(",");
        controllerPlaylist.removerMusicasDaPlaylist(idPlaylist, musicas);
        controllerPlaylist.carregarPlaylists();
        this.setVisible(false);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "ID inválido.");
    }
    }//GEN-LAST:event_btn_apagar_musicaMouseClicked

    private void btn_apagar_playlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_apagar_playlistMouseClicked
        String idStr = lbl_id_playlist.getText().trim();

    if (idStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Informe o ID da playlist.");
        return;
    }

    try {
        int idPlaylist = Integer.parseInt(idStr);
        controllerPlaylist.apagarPlaylist(idPlaylist);
        dispose(); 
        controllerPlaylist.carregarPlaylists();
        this.setVisible(false);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "ID inválido.");
    }
    }//GEN-LAST:event_btn_apagar_playlistMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_adicionar_musica;
    private javax.swing.JButton btn_apagar_musica;
    private javax.swing.JButton btn_apagar_playlist;
    private javax.swing.JButton btn_fechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lbl_id_playlist;
    private javax.swing.JTextField lbl_musica_id;
    // End of variables declaration//GEN-END:variables
}
